-- 회원정보 테이블
CREATE TABLE JIPSA_MEMBER(
ID      VARCHAR2(50)    PRIMARY KEY ,
PW      VARCHAR2(100)   NOT NULL    ,  
NAME    VARCHAR2(100)   NOT NULL    ,
TEL    VARCHAR2(100)     NOT NULL    ,
ADRESS VARCHAR2(500)    NOT NULL    ,
EMAIL  VARCHAR2(500)    NOT NULL     
);
